### ISSUE TITLE
What exactly wrong with the key here?

### ISSUE THREAD

**Issue by reubzdubz** [Rongjiehuang/GenerSpeech#6]
/content/GenerSpeech
Traceback (most recent call last):
  File "inference/GenerSpeech.py", line 35, in <module>
    GenerSpeechInfer.example_run()
  File "/content/GenerSpeech/inference/base_tts_infer.py", line 164, in example_run
    set_hparams()
  File "/content/GenerSpeech/inference/utils/hparams.py", line 94, in set_hparams
    if v in ['True', 'False'] or type(config_node[k]) in [bool, list, dict]:
KeyError: 'text'

**Comment by Rongjiehuang** [comment]
Hi, please follow the instruction for preparing pre-trained models, and this error should not occur.
